### PR TITLE
new ClassPrinter API and implementation

### PR DESCRIPTION
**Pull request by asotona**

### CODE REVIEW

**Comment by briangoetz** [comment]
I like this new API a lot more!  It is very clean -- constants, lists, 
maps.  Some questions based on past discussions:

Q: why toTree for Class and Method, but not other model types?

Q: Should "toTree" be the front door, or should it be more of an 
implementation details where we expose ClassPrinter::to{Json,Xml,Yaml} 
directly?

Q: I think we talked about having a "element name hint" in ListNode, so 
that in XML we could avoid generic "item" labels like:

     <methods>
         <item>...</item>
         <item>...</item>
     <methods>

and instead use contextually sensible labels like:

     <methods>
<method>...</method>
         <method>...</method>
     <methods>

Did you figure out a way to obviate that?

**Comment by asotona** [comment]
On 01.08.2022 18:22, "Brian Goetz" ***@***.***> wrote:

I like this new API a lot more!  It is very clean -- constants, lists,
maps.  Some questions based on past discussions:

Q: why toTree for Class and Method, but not other model types?
No problem to add it (I hope).


Q: Should "toTree" be the front door, or should it be more of an
implementation details where we expose ClassPrinter::to{Json,Xml,Yaml}
directly?

I found usefull to print actual Node during traversal (for example test is not matching, so lets print what we have).



Q: I think we talked about having a "element name hint" in ListNode, so
that in XML we could avoid generic "item" labels like:

    <methods>
        <item>...</item>
        <item>...</item>
    <methods>

and instead use contextually sensible labels like:

    <methods>
<method>...</method>
        <method>...</method>
    <methods>

Did you figure out a way to obviate that?

Entry names are hard-coded in Node::name, so every key in MapNode is duplicated in value node name.
I’ve tried many workarounds, however XML is too different from Json and Yaml, so duplication of map keys seems to be the choice.

**Comment by asotona** [comment]
Q: why toTree for Class and Method, but not other model types?

I’ve narrowed it to parent of all models: toTree(CompoundElement<?> model, Verbosity verbosity)

Q: Should "toTree" be the front door, or should it be more of an
implementation details where we expose ClassPrinter::to{Json,Xml,Yaml}
directly?

Print existing Node seems to be very useful, however not so intuitive for front door.
I’ve added default ClassPrinter::to{Json,Xml,Yaml} delegating to toTree.to{Json,Xml,Yaml}

And I found missing a way how to walk through the nodes, so I added Node::walk traversing the tree as Stream<Node>

I’m also thinking about boolean Node::match(Map<ConstantDesc, ConstantDesc> pattern), which may allow test patterns like:
//search in CP
assertTrue(classNode.walk().anyMatch(n -> n.match(Map.of(“tag”, “Class”, "class internal name","MyClass"))));
//find method
var myMethodNode = classNode.walk().filter(n -> n.match(Map.of("method name", "myMethod"”, "method type", "(I)Z"))).findAny();
assertTrue(myMethodNode.isPresent());
//or check method flags
assertTrue(myMethodNode.get().walk().anyMatch(n -> n.match(Map.of(“flag”, “PROTECTED”))));

This would allow to write a bit more sophisticated tests based on structured class prints (without deep knowledge of Classfile API).

**Comment by briangoetz** [comment]
>
> On 01.08.2022 18:22, "Brian Goetz" ***@***.***> wrote:
>
> I like this new API a lot more! It is very clean -- constants, lists,
> maps. Some questions based on past discussions:
>
> Q: why toTree for Class and Method, but not other model types?
> No problem to add it (I hope).

If it makes sense, we should do them all (alternately, only do Class), 
since I suspect we have to implement them all anyway to completely 
traverse the class anyway.

> Q: Should "toTree" be the front door, or should it be more of an
> implementation details where we expose ClassPrinter::to{Json,Xml,Yaml}
> directly?
>
> I found usefull to print actual Node during traversal (for example 
> test is not matching, so lets print what we have).

OK, so you're saying we are going to guide people who want "toXML" to 
toTree instead, and point out they can get XML out of a tree. That's 
fine, just requires some additional documentation.

> Q: I think we talked about having a "element name hint" in ListNode, so
> that in XML we could avoid generic "item" labels like:
>
> <methods>
> <item>...</item>
> <item>...</item>
> <methods>
>
> and instead use contextually sensible labels like:
>
> <methods>
> <method>...</method>
> <method>...</method>
> <methods>
>
> Did you figure out a way to obviate that?
>
> Entry names are hard-coded in Node::name, so every key in MapNode is 
> duplicated in value node name.
> I’ve tried many workarounds, however XML is too different from Json 
> and Yaml, so duplication of map keys seems to be the choice.

OK.  Can you share a few representative examples so we can see the 
characteristics of the output in different formats?

**Comment by briangoetz** [comment]
> The API actually allows to print and convert to tree any 
> CompoundElement. Or would you prefer to break it down even more to be 
> able to print individually any ClassfileElement?

Breaking down further potentially opens the door to a nice refactoring: 
if stringifying any ClassfileElement can be done through ClassPrinter, 
then we can simply have ClassFileElement::toString delegate to a CP, 
rather than duplicating the code between the element implementation and 
the CP implementation.

**Pull request merged**
